# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [2]:
v1 = np.zeros(10, dtype='int32')
v1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [3]:
v2 = np.identity(10,dtype='int32')[4,:]
v2

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int32)

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [4]:
v3 = np.arange(10,50)
v3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [5]:
v4 = np.arange(0,11)
print(v4)
v5 = v4[::-1]
print(v5)

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [7]:
v5 = np.arange(9).reshape(3,3)
v5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [8]:
v6 = np.array([1,2,0,0,4,0])
indices = np.where(v6 != 0)
indices

(array([0, 1, 4]),)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [9]:
v7 = np.random.rand(3,3)
v7

array([[0.78126428, 0.85811285, 0.90576216],
       [0.57653878, 0.69893172, 0.64739338],
       [0.77463823, 0.20986942, 0.86073714]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [10]:
v8 = np.random.randint(1000, size=(10,10))
print(v8)
min = np.min(v8)
max =np.max(v8)

print("Min value is: ", min)
print("Max value is: ", max)

[[575 583  40 104 927 742 259 784 295 786]
 [204 773 383 518 538 515  91 990  41 232]
 [744 659 692 372 820 999 115   8 391  45]
 [320 672 390 542  88 490 319 811 848 915]
 [991 550 199 479 793 218 998 919 963 195]
 [672 779 334 501 141 147 591 552 788 622]
 [857 916 801 358 952 999 267  79 868 431]
 [410 155 797 226 493 406 270  34 375 836]
 [410 234 796 428 620 869 822 168 458 783]
 [187 286 818 307 486 214 930 222 718  34]]
Min value is:  8
Max value is:  999


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [11]:
v9 = np.random.rand(30)
print(v9)
print(v9.size)
v9.mean()

[0.89341537 0.44447283 0.44613724 0.67925318 0.6486101  0.23312215
 0.29874498 0.77189318 0.64277784 0.80555623 0.81727227 0.63758174
 0.24864853 0.30313098 0.51819262 0.93511862 0.40997517 0.33162592
 0.88149638 0.89202288 0.36127    0.98473756 0.78325682 0.20531592
 0.24683259 0.17883326 0.763541   0.39905804 0.51106814 0.36483387]
30


0.5545931815767119

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [12]:
v10 = np.ones([4,4])
v11 = np.zeros([2,2])

v10[1:-1,1:-1] = v11
print(v10)




[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [13]:
v12 = np.random.randint(2000, size=[10,5])
v12[:,[0,-1]] = v12[[0,-1]] = 0
v12

array([[   0,    0,    0,    0,    0],
       [   0, 1574,  994, 1604,    0],
       [   0, 1476,   96, 1901,    0],
       [   0,  553, 1617,  448,    0],
       [   0,  468, 1571,  254,    0],
       [   0,  997,  650,  706,    0],
       [   0,   86,  757,  976,    0],
       [   0, 1277,  761,  122,    0],
       [   0,  316,  364, 1343,    0],
       [   0,    0,    0,    0,    0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [14]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [15]:
v13 = np.arange(5,30).reshape(5,5)
v13[[1,2,3,4],[0,1,2,3]] = [1,2,3,4]
v13

array([[ 5,  6,  7,  8,  9],
       [ 1, 11, 12, 13, 14],
       [15,  2, 17, 18, 19],
       [20, 21,  3, 23, 24],
       [25, 26, 27,  4, 29]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [16]:
v14 = np.arange(336).reshape(6,7,8)
result = np.where(v14 == 100)
print(result)
print(v14[result])

(array([1]), array([5]), array([4]))
[100]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [71]:
a = np.arange(0,27,3).reshape(3,3)
print(a)
row_sums = a.sum(axis=1)
print(row_sums)
new_matrix = a / row_sums[:, np.newaxis]
print(new_matrix)

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]
[ 9 36 63]
[[0.         0.33333333 0.66666667]
 [0.25       0.33333333 0.41666667]
 [0.28571429 0.33333333 0.38095238]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [17]:
v16 = np.arange(15)
print(v16)
v16[4:8] = -v16[4:8]
print(v16)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


#### 29. How to round away from zero a float array ? (★☆☆)

In [18]:
v17 = np.array([1.782, 23.2938, 0.3293, -0.232, -1.8], dtype="float")
print(v17)
np.ceil(v17)

[ 1.782  23.2938  0.3293 -0.232  -1.8   ]


array([ 2., 24.,  1., -0., -1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [19]:
v18 = np.array([2, 4, 7, 1, 5])
v19 = np.array([7, 3, 9, 0, 5])

v20 = np.intersect1d(v18, v19)
  
print( v20)

[5 7]


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [20]:
#it is false
v19 = np.arange(-1,2)
print(v19)
np.sqrt(v19) == np.emath.sqrt(v19)

[-1  0  1]


<ipython-input-20-fd621874f8b0>:4: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(v19) == np.emath.sqrt(v19)


array([False,  True,  True])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [21]:
v20 = np.random.randint(100, size=(10,))
v20

array([56, 97, 84,  2,  8, 64, 76, 54, 19, 48])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [22]:
v21 = np.random.rand(10,)
v21

array([0.46676084, 0.84747239, 0.79101299, 0.16332449, 0.81165745,
       0.50961498, 0.62034347, 0.58811369, 0.20501827, 0.30934593])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [23]:
v22 = np.random.randint(10, size=(10,))
print(v22)
np.sort(v22)

[1 6 4 8 3 1 5 1 5 2]


array([1, 1, 1, 2, 3, 4, 5, 5, 6, 8])

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [24]:
v23 = np.random.randint(10, size=(10,))
v24 = np.random.randint(10, size=(10,))

print(v23)
print(v24)
np.all(v23 == v24)

[0 5 4 2 8 5 0 4 9 8]
[4 5 1 3 9 5 8 4 2 2]


False

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [25]:
v25 = np.random.randint(100, size=(10,))
print(v25)
print(np.max(v25))
print(np.argmax(v25))
v25[np.argmax(v25)] = 0
print(v25)


[33 60 87 71 71 34 28  8  8 39]
87
2
[33 60  0 71 71 34 28  8  8 39]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [26]:
v26 = np.arange(100)
print(v26)
v27 = np.random.uniform(0,100)
print(v27)
index = (np.abs(v26-v27)).argmin()
print(v26[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
2.352626320731077
2


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [27]:
v28 = np.array([1.34, 7.5444, 93.493, 18.2039], dtype='float32')
print(v28.dtype)
v28 = v28.astype('int32')
print(v28)
print(v28.dtype)


float32
[ 1  7 93 18]
int32


#### 59. How to sort an array by the nth column? (★★☆)

In [28]:
v29 = np.random.randint(100, size=(5,5))
print(v29)

v29 = np.take_along_axis(v29, v29.argsort(axis=0), axis=0)
print(v29)

[[83 42 88 59 26]
 [95  4 32 51 58]
 [72 32 62 81 38]
 [90 14 69 80 65]
 [54 33 69 68 27]]
[[54  4 32 51 26]
 [72 14 62 59 27]
 [83 32 69 68 38]
 [90 33 69 80 58]
 [95 42 88 81 65]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [29]:
v30 = np.ones((3,3))
v30[:,1]= 0
print(v30)
np.all(v30 == 0, axis =0)

[[1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]]


array([False,  True, False])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [30]:
v31 = np.array([1,2,3,4,5])
v32 = np.zeros(17)
v32[0::4] = v31
print(v32)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 72. How to swap two rows of an array? (★★★)

In [31]:
v33 = np.arange(10).reshape(2,5)
print(v33)
v33[[0,1]] = v33[[1,0]]
print(v33)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[5 6 7 8 9]
 [0 1 2 3 4]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [32]:
v34 = np.array([1.34, 7.5444, 93.493, 18.2039], dtype='float32')
print(v34)
# Negate a boolean
print(~(v34 > 50))

#change the sign of a float inplace
print((np.negative(v34, out=v34)))

[ 1.34    7.5444 93.493  18.2039]
[ True  True False  True]
[ -1.34    -7.5444 -93.493  -18.2039]


#### 83. How to find the most frequent value in an array?

In [40]:
v35 = np.random.randint(5, size=(20,))
print(v35)
counts = np.bincount(v35)
print(counts.argmax())

[3 4 0 3 3 1 4 4 1 0 4 2 3 3 1 2 1 1 4 3]
3


#### 89. How to get the n largest values of an array (★★★)

In [103]:
numbers = np.random.randint(1024, size=(100,))
n = 4

idx = np.argpartition(numbers, -n)[-n:]
indices = idx[np.argsort((-numbers)[idx])]

print(numbers[indices])

[1012 1011 1005 1005]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [62]:
v37 = np.random.randint(2, size=(3,3))
print(v37)

unique_rows = np.unique(v37, axis=0)
print("----")
print(unique_rows)

[[1 1 1]
 [1 1 1]
 [1 0 0]]
----
[[1 0 0]
 [1 1 1]]
